/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloworldService_H
#define HelloworldService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "helloworld_types.h"

namespace helloworld {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloworldServiceIf {
 public:
  virtual ~HelloworldServiceIf() {}
  virtual void getHelloworld(std::string& _return) = 0;
};

class HelloworldServiceIfFactory {
 public:
  typedef HelloworldServiceIf Handler;

  virtual ~HelloworldServiceIfFactory() {}

  virtual HelloworldServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloworldServiceIf* /* handler */) = 0;
};

class HelloworldServiceIfSingletonFactory : virtual public HelloworldServiceIfFactory {
 public:
  HelloworldServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf>& iface) : iface_(iface) {}
  virtual ~HelloworldServiceIfSingletonFactory() {}

  virtual HelloworldServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloworldServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> iface_;
};

class HelloworldServiceNull : virtual public HelloworldServiceIf {
 public:
  virtual ~HelloworldServiceNull() {}
  void getHelloworld(std::string& /* _return */) {
    return;
  }
};


class HelloworldService_getHelloworld_args {
 public:

  HelloworldService_getHelloworld_args(const HelloworldService_getHelloworld_args&);
  HelloworldService_getHelloworld_args& operator=(const HelloworldService_getHelloworld_args&);
  HelloworldService_getHelloworld_args() {
  }

  virtual ~HelloworldService_getHelloworld_args() throw();

  bool operator == (const HelloworldService_getHelloworld_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const HelloworldService_getHelloworld_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloworldService_getHelloworld_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloworldService_getHelloworld_pargs {
 public:


  virtual ~HelloworldService_getHelloworld_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloworldService_getHelloworld_result__isset {
  _HelloworldService_getHelloworld_result__isset() : success(false) {}
  bool success :1;
} _HelloworldService_getHelloworld_result__isset;

class HelloworldService_getHelloworld_result {
 public:

  HelloworldService_getHelloworld_result(const HelloworldService_getHelloworld_result&);
  HelloworldService_getHelloworld_result& operator=(const HelloworldService_getHelloworld_result&);
  HelloworldService_getHelloworld_result() : success() {
  }

  virtual ~HelloworldService_getHelloworld_result() throw();
  std::string success;

  _HelloworldService_getHelloworld_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const HelloworldService_getHelloworld_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloworldService_getHelloworld_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloworldService_getHelloworld_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloworldService_getHelloworld_presult__isset {
  _HelloworldService_getHelloworld_presult__isset() : success(false) {}
  bool success :1;
} _HelloworldService_getHelloworld_presult__isset;

class HelloworldService_getHelloworld_presult {
 public:


  virtual ~HelloworldService_getHelloworld_presult() throw();
  std::string* success;

  _HelloworldService_getHelloworld_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloworldServiceClient : virtual public HelloworldServiceIf {
 public:
  HelloworldServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloworldServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getHelloworld(std::string& _return);
  void send_getHelloworld();
  void recv_getHelloworld(std::string& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloworldServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloworldServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getHelloworld(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloworldServiceProcessor(::apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> iface) :
    iface_(iface) {
    processMap_["getHelloworld"] = &HelloworldServiceProcessor::process_getHelloworld;
  }

  virtual ~HelloworldServiceProcessor() {}
};

class HelloworldServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloworldServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< HelloworldServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< HelloworldServiceIfFactory > handlerFactory_;
};

class HelloworldServiceMultiface : virtual public HelloworldServiceIf {
 public:
  HelloworldServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloworldServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> > ifaces_;
  HelloworldServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<HelloworldServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getHelloworld(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getHelloworld(_return);
    }
    ifaces_[i]->getHelloworld(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloworldServiceConcurrentClient : virtual public HelloworldServiceIf {
 public:
  HelloworldServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloworldServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getHelloworld(std::string& _return);
  int32_t send_getHelloworld();
  void recv_getHelloworld(std::string& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
