/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TransferService_H
#define TransferService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "helloworld_types.h"

namespace helloworld {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class TransferServiceIf {
 public:
  virtual ~TransferServiceIf() {}
  virtual void transfer(std::string& _return) = 0;
};

class TransferServiceIfFactory {
 public:
  typedef TransferServiceIf Handler;

  virtual ~TransferServiceIfFactory() {}

  virtual TransferServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TransferServiceIf* /* handler */) = 0;
};

class TransferServiceIfSingletonFactory : virtual public TransferServiceIfFactory {
 public:
  TransferServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf>& iface) : iface_(iface) {}
  virtual ~TransferServiceIfSingletonFactory() {}

  virtual TransferServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TransferServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface_;
};

class TransferServiceNull : virtual public TransferServiceIf {
 public:
  virtual ~TransferServiceNull() {}
  void transfer(std::string& /* _return */) {
    return;
  }
};


class TransferService_transfer_args {
 public:

  TransferService_transfer_args(const TransferService_transfer_args&);
  TransferService_transfer_args& operator=(const TransferService_transfer_args&);
  TransferService_transfer_args() {
  }

  virtual ~TransferService_transfer_args() throw();

  bool operator == (const TransferService_transfer_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const TransferService_transfer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_transfer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TransferService_transfer_pargs {
 public:


  virtual ~TransferService_transfer_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_transfer_result__isset {
  _TransferService_transfer_result__isset() : success(false) {}
  bool success :1;
} _TransferService_transfer_result__isset;

class TransferService_transfer_result {
 public:

  TransferService_transfer_result(const TransferService_transfer_result&);
  TransferService_transfer_result& operator=(const TransferService_transfer_result&);
  TransferService_transfer_result() : success() {
  }

  virtual ~TransferService_transfer_result() throw();
  std::string success;

  _TransferService_transfer_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const TransferService_transfer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TransferService_transfer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TransferService_transfer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TransferService_transfer_presult__isset {
  _TransferService_transfer_presult__isset() : success(false) {}
  bool success :1;
} _TransferService_transfer_presult__isset;

class TransferService_transfer_presult {
 public:


  virtual ~TransferService_transfer_presult() throw();
  std::string* success;

  _TransferService_transfer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TransferServiceClient : virtual public TransferServiceIf {
 public:
  TransferServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TransferServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void transfer(std::string& _return);
  void send_transfer();
  void recv_transfer(std::string& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TransferServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TransferServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_transfer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TransferServiceProcessor(::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface) :
    iface_(iface) {
    processMap_["transfer"] = &TransferServiceProcessor::process_transfer;
  }

  virtual ~TransferServiceProcessor() {}
};

class TransferServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TransferServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< TransferServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< TransferServiceIfFactory > handlerFactory_;
};

class TransferServiceMultiface : virtual public TransferServiceIf {
 public:
  TransferServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<TransferServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TransferServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<TransferServiceIf> > ifaces_;
  TransferServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<TransferServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void transfer(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->transfer(_return);
    }
    ifaces_[i]->transfer(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class TransferServiceConcurrentClient : virtual public TransferServiceIf {
 public:
  TransferServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TransferServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void transfer(std::string& _return);
  int32_t send_transfer();
  void recv_transfer(std::string& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
